<?php
/**
 * @author     Marco Schauer <marco.schauer@darkdevelopers.de.de>
 * @copyright  2019 Marco Schauer
 */

namespace Vof\Admin\Test;

use Tests\TestCase;
use Vof\Admin\Models\Admin;

/**
 * Class DemoTest
 * @package Vof\Admin\Test
 */
class LoginTest extends TestCase
{
    public $factory = null;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->factory = \Illuminate\Database\Eloquent\Factory::construct(\Faker\Factory::create(), dirname(__DIR__ . '/../src/database/factories'));
    }

    /**
     * @test
     */
    public function testLoginPageIsLoading()
    {
        $response = $this->get("/admin");

        $response->assertStatus(200);
    }

    /**
     * @test
     */
    public function testAdminCanBeCreated()
    {
        $admin = factory(Admin::class)->create();
        var_dump($admin);
    }
}
